[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lamports_vault = "5vPoyD7QHajq9SSbbyLQpEUqTcMBq29VMHmPccc6RraQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
